### ISSUE TITLE
Продумать представление города

### ISSUE THREAD

**Issue by gbagretsov** [nshindarev/MAS_Carpooling#2]
Например, матрица инциденций

**Comment by gbagretsov** [comment]
У каждой дуги длина (например, в километрах)

**Comment by nshindarev** [comment]
![1](https://cloud.githubusercontent.com/assets/9587600/24587753/df82ba32-17c4-11e7-8802-dcaf92e7488d.jpg)

**Comment by nshindarev** [comment]
Залил представление города. Использовал либу jgrapht. Всё описано в Вики.

**Comment by nshindarev** [comment]
Город, который используется по умолчанию
![1](https://cloud.githubusercontent.com/assets/9587600/24591413/4ed1df14-1809-11e7-889d-a2da0b061043.jpg)
