### ISSUE TITLE
Продумать систему диалогов водителя и пассажира

### ISSUE THREAD

**Issue by gbagretsov** [nshindarev/MAS_Carpooling#22]
1. Изучить встроенные протоколы, может, найдётся что-нибудь полезное
2. Описать спецификации протокола общения (название, перформатив, содержание сообщений и т.п.)

**Comment by gbagretsov** [comment]
https://github.com/nshindarev/MAS_Carpooling/wiki/%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0-%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%B0-%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8F-%D0%B8-%D0%BF%D0%B0%D1%81%D1%81%D0%B0%D0%B6%D0%B8%D1%80%D0%B0

**Comment by gbagretsov** [comment]
Пассажир:
исп. ReceiverBehaviour, SequenceBehaviour

**Comment by gbagretsov** [comment]
Добавить ещё подтверждение транзакции от водителя

**Comment by nshindarev** [comment]
Изучил поведение `HandleDriversList`. В текущей реализации мы вроде ждем пока все ответят, не?

**Comment by nshindarev** [comment]
а, или ты там установил срок ожидания сообщений? Тогда вопрос закрыт

**Comment by gbagretsov** [comment]
Система сообщений продумана. Далее задачи #29 и #30.
