### ISSUE TITLE
Bug: вылет некоторых агентов при запуске

### ISSUE THREAD

**Issue by nshindarev** [nshindarev/MAS_Carpooling#23]
При таких конфигах:
 `-count_agents 5 -auto_generate no -count_driver 3 -delay_agents 4 ` 
прога немного отрабатывает и вылетает какая-то дичь 
![image](https://cloud.githubusercontent.com/assets/9587600/24856527/b4bcaf4a-1ded-11e7-84d8-3dfb8e0e7b0b.png)

**Comment by nbirillo** [comment]
Возможно это связано с задержкой пр  генерации? с остальными параметрами все ок

**Comment by gbagretsov** [comment]
`-auto_generate no` стоит, по идее, эти параметры вообще не должны влиять ни на что. Но попробуй задержку поставить больше, например, 5000, посмотри, что будет. Но задержка тоже не должна влиять

**Comment by gbagretsov** [comment]
Невоспроизводимо.

Попробуй сделать вот что:
Выбери Tools -> Show DF GUI. После этого **в главном окне** ПКМ по агенту-водителю -> Kill Agent. Затем посмотри, исчез ли он в DF GUI или опять вылетает исключение.

**Comment by nshindarev** [comment]
Сделал так как ты сказал. Агент исчез в DF GUI, никаких исключений

**Comment by nshindarev** [comment]
Ошибка никуда не делась. Могу попробовать откатиться на свою ветку старую и попробовать еще раз смерджить

**Comment by gbagretsov** [comment]
Значит проблема не в методе `takeDown`, это хорошо. Проблема именно в аварийном завершении. Вообще, скорее всего это только на MAC такое происходит (если Настя у себя запустит, то сможем подтвердить или опровергнуть это утверждение). У меня ничего не ломается, как я и писал раньше. Думаю, здесь мы ничего не сможем сделать, можно закрывать. Главное, что сама по себе программа работает.

**Comment by nshindarev** [comment]
![image](https://cloud.githubusercontent.com/assets/9587600/25256347/c7cd5258-2638-11e7-8630-bdd1308ba3dc.png)
ТА-ДАААААААА

**Comment by gbagretsov** [comment]
Вряд ли сможем решить эту проблему адекватно. Если ставить задержку при генерации агентов, вроде не вылетает
