### ISSUE TITLE
Характер взаимодействия с YP

### ISSUE THREAD

**Issue by nshindarev** [nshindarev/MAS_Carpooling#24]
Предлагается одноразовый проход citizen по сервису YP с целью выявить водил, которые будут проезжать через районы нужные citizen и отсеять тех, чей маршрут не подходит.

Далее предполагается отправить сообщения всем подходящим водилам и ждать от них ответа
![1](https://cloud.githubusercontent.com/assets/9587600/24857884/80981e3e-1df2-11e7-93f8-3c43b5fabea7.jpg)

**Comment by nshindarev** [comment]
Таким образом предлагается поменять TickerBehaviour на OneShot

**Comment by gbagretsov** [comment]
Предлагаю постоянно просматривать список водил (с интервалом определённым). Проблем я особо не вижу при таком подходе. Новые водилы просто будут добавляться в список сохранённых (в принципе, это так сейчас и работает). А другое поведение будет этот список обрабатывать, тоже с определённым интервалом. Плюс такого подхода - есть шанс найти подходящего водителя, даже если он создастся позже других (так как у нас агенты появляются с задержкой).

P.S. Схему ещё не смотрел

**Comment by nshindarev** [comment]
Хорошо, с таким подходом согласен.

**Comment by gbagretsov** [comment]
Для общения с водилами мы выделим новое поведение, чтобы не нарушать гибкости и семантики

**Comment by nshindarev** [comment]
И тут согласен, разумеется

**Comment by nshindarev** [comment]
Так вот я пока что не вижу проблем с тем, чтобы всё это дело параллелить, так как у нас каждый водитель имеет свой пул сообщений из которого их поочередно вытаскивает и обрабатывает. В момент когда все места будут забиты он убирает себя из YP, а остальным оставшимся в пуле шлёт сообщение в формате: "отказано по причине нехватки свободных мест". (это чтобы не путать с отказом по причине предложения малой цены). В случае когда появляется новый пассажир, необходимо также оповестить всех остальных пассажиров что им нужно будет меньше денег уплатить, так как бензин теперь делится на большее количество попутчиков. 

Может, объяснишь где тут трудности, а то я пока детально с логикой реализации не копался 🔢

**Comment by nshindarev** [comment]
Короче, я погнал на пару, обсудим в унике

**Comment by gbagretsov** [comment]
Под словом "распараллелить" я имел в виду, что вдвоём это трудно реализовывать, нужно заранее все спецификации сообщений прописать

**Comment by gbagretsov** [comment]
Предлагаю закрыть эту задачу и перенести обсуждение в #22. С Yellow Pages более-менее разобрались

**Comment by gbagretsov** [comment]
YP вроде как работает нормально, закрываем
