### ISSUE TITLE
Сбор статистики

### ISSUE THREAD

**Issue by gbagretsov** [nshindarev/MAS_Carpooling#25]
Итоговый вывод:

Для всех водителей:
Водитель: маршрут такой-то, пассажиры такие-то

Суммарный пробег всех машин: такой-то

**Comment by nbirillo** [comment]
Добавлен сборщик статистики. 

Водитель должен отправить сообщение сборщику `secretary` с перформативом INFORM и контентом: 
`agent_1,agent_2,...,1,2,3,...` - сначала через запятую пассажиры, затем маршрут
