### ISSUE TITLE
Реализовать конечный автомат для пассажира

### ISSUE THREAD

**Issue by nshindarev** [nshindarev/MAS_Carpooling#30]

**Comment by gbagretsov** [comment]
http://imgdepo.com/id/10554631.jpg

Нужно проверить работу состояния ожидания завершения транзакции. Всё остальное вроде как работает.

**Comment by gbagretsov** [comment]
Вроде работает. По крайней мере, ничего не вылетает, в логах бреда не наблюдается, агенты-пассажиры вкидывают предложения и адекватно на них реагируют.
