### ISSUE TITLE
Доделать ConfirmTransactionState

### ISSUE THREAD

**Issue by nshindarev** [nshindarev/MAS_Carpooling#32]
Нужно удалять пассажирское поведение и дерегистрировать себя из YP
 (сори, с ходу не нашел как это делать)

**Comment by nshindarev** [comment]
Так. Я вспомнил, что у Агента есть `takedown()`, одной проблемой меньше

**Comment by gbagretsov** [comment]
У агента также есть `removeBehaviour`

**Comment by gbagretsov** [comment]
`takeDown()` немного про другое. Это когда агент умирает. Но да, там сейчас `deregister` вызывается, можешь оттуда взять код

**Comment by gbagretsov** [comment]
Ещё отправь остальным `REJECT_PROPOSAL` с сообщением `Conversation.NO_SEATS`

**Comment by gbagretsov** [comment]
Сделано
